/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package utfpr.gui;

import utfpr.banco.ContaBancaria;

/**
 *
 * @author felip
 */
public class ContaSaldoDialog extends javax.swing.JDialog {

    /**
     * Creates new form ContaMenorSaldoDialog
     */
    public ContaSaldoDialog(java.awt.Frame parent, boolean modal, ContaBancaria conta, String text) {
        super(parent, modal);
        initComponents();
        textLabel.setText(text);
        contaMenorSaldoLabel.setText(conta.getInformacoes());
        contaMenorSaldoLabel.setText(String.valueOf(conta.getInformacoes()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textLabel = new javax.swing.JLabel();
        contaMenorSaldoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(585, 150));
        getContentPane().setLayout(null);

        textLabel.setBackground(new java.awt.Color(255, 255, 255));
        textLabel.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        textLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        textLabel.setText("jLabel1");
        textLabel.setToolTipText("");
        textLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        getContentPane().add(textLabel);
        textLabel.setBounds(24, 16, 340, 20);

        contaMenorSaldoLabel.setBackground(new java.awt.Color(255, 255, 255));
        contaMenorSaldoLabel.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        contaMenorSaldoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        contaMenorSaldoLabel.setText("          jLabel2");
        contaMenorSaldoLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        contaMenorSaldoLabel.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        contaMenorSaldoLabel.setOpaque(true);
        getContentPane().add(contaMenorSaldoLabel);
        contaMenorSaldoLabel.setBounds(24, 42, 540, 56);

        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Users\\Felippe\\Área de Trabalho 2\\poo_trab\\po23s-cch\\src\\main\\java\\utfpr\\gui\\fundoutfpr.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 590, 150);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contaMenorSaldoLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel textLabel;
    // End of variables declaration//GEN-END:variables
}
