package utfpr.gui;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import utfpr.banco.ContaBancaria;
import utfpr.banco.Banco;
import utfpr.banco.ContaCorrente;
import utfpr.banco.ContaPoupanca;
import utfpr.util.DataProvider;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author felip
 */
public class NewJFrame extends javax.swing.JFrame {
    DefaultListModel modeloListaContas = new DefaultListModel();
    ArrayList<ContaBancaria> listaDeContas = new ArrayList<ContaBancaria>();
    

    public NewJFrame(ArrayList<ContaBancaria> contas) {
        initComponents();
        accountsListFrame.setModel(modeloListaContas);
        carregarLista(contas);
        
        ArrayList<ContaPoupanca> listaDeContasPoupanca = Banco.listaDeContasPoupanca(contas);
        ArrayList<ContaCorrente> listaDeContasCorrente = Banco.listaDeContasCorrente(contas);
        
        saldoMedioLabel.setText(Banco.saldoMedio(contas));
        saldoMedioCCLabel.setText(Banco.saldoMedioContaCorrente(listaDeContasCorrente));
        saldoMedioCPLabel.setText(Banco.saldoMedioContaPoupanca(listaDeContasPoupanca));
    }

    private void carregarLista(ArrayList<ContaBancaria> contas){
        for(int i = 0; i < contas.size(); i++){
         modeloListaContas.addElement(contas.get(i).getInformacoes());
         listaDeContas.add(contas.get(i));
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        accountsListFrame = new javax.swing.JList<>();
        saldoMedioCCLabel = new javax.swing.JLabel();
        saldoMedioLabel = new javax.swing.JLabel();
        saldoMedioCPLabel = new javax.swing.JLabel();
        contaMaiorSaldoButton = new javax.swing.JButton();
        contaMenorSaldoButton = new javax.swing.JButton();
        listaDeClientesButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setFont(new java.awt.Font("Bookman Old Style", 0, 10)); // NOI18N
        setForeground(new java.awt.Color(102, 102, 255));
        setMinimumSize(new java.awt.Dimension(800, 450));
        setSize(new java.awt.Dimension(1000, 800));
        getContentPane().setLayout(null);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 120, 36));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("BANCO UTFPR");
        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 107, 49), 3));
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 6, 630, 40);

        jLabel1.setBackground(new java.awt.Color(172, 11, 176));
        jLabel1.setFont(new java.awt.Font("Bookman Old Style", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Users\\Felippe\\Área de Trabalho 2\\poo_trab\\po23s-cch\\src\\main\\java\\utfpr\\gui\\fundoutfpr.png")); // NOI18N
        jLabel1.setText("Banco da UTFPR");
        jLabel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 890, 50);

        accountsListFrame.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        accountsListFrame.setFont(new java.awt.Font("Bookman Old Style", 0, 10)); // NOI18N
        accountsListFrame.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        accountsListFrame.setToolTipText("");
        jScrollPane1.setViewportView(accountsListFrame);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 83, 443, 208);

        saldoMedioCCLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saldoMedioCCLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        saldoMedioCCLabel.setOpaque(true);
        getContentPane().add(saldoMedioCCLabel);
        saldoMedioCCLabel.setBounds(480, 190, 80, 25);

        saldoMedioLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saldoMedioLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        saldoMedioLabel.setOpaque(true);
        getContentPane().add(saldoMedioLabel);
        saldoMedioLabel.setBounds(480, 110, 80, 25);

        saldoMedioCPLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        saldoMedioCPLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        saldoMedioCPLabel.setOpaque(true);
        getContentPane().add(saldoMedioCPLabel);
        saldoMedioCPLabel.setBounds(480, 265, 80, 25);

        contaMaiorSaldoButton.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        contaMaiorSaldoButton.setText("Conta Maior Saldo");
        contaMaiorSaldoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contaMaiorSaldoHandler(evt);
            }
        });
        getContentPane().add(contaMaiorSaldoButton);
        contaMaiorSaldoButton.setBounds(20, 330, 150, 30);

        contaMenorSaldoButton.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        contaMenorSaldoButton.setText("Conta Menor Saldo");
        contaMenorSaldoButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                contaMenorSaldoHandler(evt);
            }
        });
        getContentPane().add(contaMenorSaldoButton);
        contaMenorSaldoButton.setBounds(180, 330, 150, 30);

        listaDeClientesButton.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        listaDeClientesButton.setText("Lista de Clientes");
        listaDeClientesButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaDeClientesHandler(evt);
            }
        });
        getContentPane().add(listaDeClientesButton);
        listaDeClientesButton.setBounds(340, 330, 150, 30);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Saldo Médio Contas:");
        jLabel2.setToolTipText("");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(480, 83, 170, 25);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Saldo Médio C. Corrente:");
        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel3.setMaximumSize(new java.awt.Dimension(158, 17));
        jLabel3.setMinimumSize(new java.awt.Dimension(158, 17));
        jLabel3.setOpaque(true);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(480, 163, 170, 25);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Bookman Old Style", 0, 12)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Saldo Médio C. Poupança:");
        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(480, 237, 170, 25);

        jLabel5.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Lista de Contas do Banco:");
        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 58, 440, 20);

        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\Users\\Felippe\\Área de Trabalho 2\\poo_trab\\po23s-cch\\src\\main\\java\\utfpr\\gui\\fundoutfpr.png")); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-130, -10, 1120, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaDeClientesHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaDeClientesHandler
    new ListaDeClientesDialog(this, true, listaDeContas).setVisible(true);
    }//GEN-LAST:event_listaDeClientesHandler

    private void contaMenorSaldoHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contaMenorSaldoHandler
      new ContaSaldoDialog(this, true, Banco.menorSaldo(listaDeContas), "Conta com Menor Saldo:").setVisible(true);
    }//GEN-LAST:event_contaMenorSaldoHandler

    private void contaMaiorSaldoHandler(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contaMaiorSaldoHandler
       new ContaSaldoDialog(this, true, Banco.maiorSaldo(listaDeContas), "Conta com Maior Saldo:").setVisible(true);
    }//GEN-LAST:event_contaMaiorSaldoHandler

    /**
     * @param args the command line arguments
     * 
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             DataProvider provider = new DataProvider();
             Banco banco = provider.criarBanco("UTFPR");
             ArrayList<ContaBancaria> contas = banco.getAllAccounts();
             new NewJFrame(contas).setVisible(true);
            }
        }
        );
        
        

    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> accountsListFrame;
    private javax.swing.JButton contaMaiorSaldoButton;
    private javax.swing.JButton contaMenorSaldoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton listaDeClientesButton;
    private javax.swing.JLabel saldoMedioCCLabel;
    private javax.swing.JLabel saldoMedioCPLabel;
    private javax.swing.JLabel saldoMedioLabel;
    // End of variables declaration//GEN-END:variables
}
